name: Build and Publish Electron GUI

on:
  push:
    tags:
      - "deemix-gui@*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  HUSKY: 0

jobs:
  build-release-electron:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm build:gui

      - name: Upload Artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            gui/dist/deemix-gui_*.dmg
            gui/dist/deemix-gui.exe
            gui/dist/deemix-gui_setup.exe
            gui/dist/deemix-gui.AppImage
            gui/dist/deemix-gui.deb
